
export const projectData = [
  {
    image: "/work/computech-front.png",
    category: "Next js",
    name: "Computech",
    teckStacks: ["React", "Prisma", "ReactQuery"],
    description: "Electronics store from Jeddah, Saudi Arabia",
    link: "https://www.compu-tech.com.sa",
    github: "https://github.com/lucmanm/nextjs_ecommerce_computech_storefront",
  },
  {
    image: "/work/2.png",
    category: "Next js",
    name: "Playground",
    description: "All I keep my web development and test applications",
    link: "https://playground-hazel-six.vercel.app/",
    github: "https://github.com/lucmanm/playground",
  },
  {
    image: "/work/3.png",
    category: "Admin Dashboard",
    name: "Nexa Website",
    teckStacks: ["React"],
    description: "A Simple frontend application admin dashboard contains basic react usage",
    link: "https://lucmanm-admin-dashboard.netlify.app/",
    github: "https://github.com/lucmanm/admin-dashboard",
  },
  {
    image: "/work/4.png",
    category: "Javascript",
    name: "Nexa Website",
    teckStacks: ["React", "Nextjs"],
    description: "Simplete project about car data is fetch from rest api cars",
    link: "https://next-project-car-showcase.vercel.app/",
    github: "https://github.com/lucmanm/nextjs_car_showcase",
  },
  {
    image: "/work/4.png",
    category: "Expo ",
    name: "Projects App",
    teckStacks: ["React"],
    description: "This contains about projects only like for resume",
    link: "projects-app-tau.vercel.app",
    github: "https://github.com/lucmanm/nextjs_projects_app",
  },
] as const;